# Generated by Django 5.2.6 on 2025-09-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('detalle', models.TextField()),
            ],
        ),
    ]
