# Generated by Django 5.2.3 on 2025-09-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteo', '0002_replica'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replica',
            name='numero',
            field=models.SmallIntegerField(default=0.1),
            preserve_default=False,
        ),
    ]
