# Generated by Django 5.2.3 on 2025-09-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteo', '0003_noticia_imagen_replica_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
    ]
